[package]
name = "tensoru"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.41"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.0"
objc2-metal = { version = "0.3.0", features = ["MTLDevice"] }

[dev-dependencies]
tracing-test = "0.2.5"
